### PR TITLE
make connection, request, and socket timeouts configurable

### LINKED ISSUE #121: Add (socket) timeout support in configuration options
For "complex" queries to an elasticsearch instance with significant data (e.g. over 5M documents), I get the following error:
```
{ 2058 rufus-scheduler intercepted an error:
  2058   job:
  2058     Rufus::Scheduler::CronJob "* * * * *" {}
  2058   error:
  2058     2058
  2058     Manticore::SocketTimeout
  2058     Read timed out
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:37:in `block in initialize'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:79:in `call'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:274:in `call_once'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:158:in `code'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/manticore.rb:85:in `block in perform_request'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/base.rb:262:in `perform_request'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/transport/http/manticore.rb:68:in `perform_request'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-transport-5.0.5/lib/elasticsearch/transport/client.rb:131:in `perform_request'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/elasticsearch-api-5.0.5/lib/elasticsearch/api/actions/search.rb:183:in `search'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/logstash-input-elasticsearch-4.5.0/lib/logstash/inputs/elasticsearch.rb:298:in `search_request'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/logstash-input-elasticsearch-4.5.0/lib/logstash/inputs/elasticsearch.rb:246:in `do_run_slice'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/logstash-input-elasticsearch-4.5.0/lib/logstash/inputs/elasticsearch.rb:227:in `do_run'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/logstash-input-elasticsearch-4.5.0/lib/logstash/inputs/elasticsearch.rb:210:in `block in run'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:234:in `do_call'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:258:in `do_trigger'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:300:in `block in start_work_thread'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:299:in `block in start_work_thread'
  2058       org/jruby/RubyKernel.java:1446:in `loop'
  2058       /home/user/opt/logstash-7.6.1/vendor/bundle/jruby/2.5.0/gems/rufus-scheduler-3.0.9/lib/rufus/scheduler/jobs.rb:289:in `block in start_work_thread'
```

It seems like when the query takes too much time to get an answer, I get the SocketTimeout error.
When setting a custom socket_timeout in the transport_options to 120s, I do not get the error anymore.
This has been done by changing directly `elasticsearch.rb`, l177:
```
transport_options = {:socket_timeout => 120}
```

Could it be possible to have a new configuration option for the input plugin to set the socket_timeout?

If needed I could submit a PR.

- Version: 4.5.0
- Operating System: Linux
- Config File:
```
input {
  elasticsearch {
    hosts => [ "elasticsearch:9200" ]
    index => "myindex.*"
    query => '{"query":{"function_score":{"query":{"bool":{"must":[{"exists":{"field":"win"}},{"exists":{"field":"request"}},{"exists":{"field":"processed"}}]}},"random_score":{}}},"size":5000}'
    schedule => "* * * * *"
    scroll => "2m"
  }
}
```

### PR DESCRIPTION
**Pull request by yaauie**
default values were chosen from the current default behaviour of these
transport options as provided by the Manticore transport adapter we provide to
the Elasticsearch Client:

> ~~~
> request_timeout (integer) — default: 60 — Sets the timeout for requests.
> connect_timeout (integer) — default: 10 — Sets the timeout for connections.
> socket_timeout (integer)  — default: 10 — Sets `SO_TIMEOUT` for open connections. A value of 0 is an infinite timeout.
> ~~~
>
> -- [Manticore::Client#initialize](https://www.rubydoc.info/gems/manticore/Manticore/Client#initialize-instance_method)

I have elected _not_ to allow an infinite `socket_timeout` by requiring
the provided value to be positive, as I can see no valid use-case of such
using Elasticsearch's HTTP API.

Resolves #121

***

Includes a minor refactor of a separate custom validator to enable us to keep their logics separate.

### CODE REVIEW

File: lib/logstash/inputs/elasticsearch.rb [hunk 1]
```diff
@@ -439,4 +436,42 @@ def parse_user_password_from_cloud_auth(cloud_auth)
     [ cloud_auth.username, cloud_auth.password ]
   end
 
+  module URIOrEmptyValidator
```
Comment (colinsurprenant) [inline lib/logstash/inputs/elasticsearch.rb:439]: just to verify: this is an unrelated cleanup right? not problem including it but just wanted to make sure.

**Comment by colinsurprenant** [comment]
LGTM pending a inline clarification.

**Comment by colinsurprenant** [comment]
Build errors seems network timeout related, I restarted them.

File: lib/logstash/inputs/elasticsearch.rb (hunk 1 above)
Comment (yaauie) [reply lib/logstash/inputs/elasticsearch.rb:439]: Yes, that is why it is in a separate commit with a message to that effect.

Comment (colinsurprenant) [reply lib/logstash/inputs/elasticsearch.rb:439]: ah, missed that, thanks.
